@startuml

actor Contributor
actor QA
actor CommunityMember
actor Supervisor
actor Assessor
actor Sponsor

Contributor -> Contribution : creates
QA -> Contribution : approves
CommunityMember -> Contribution : gives feedback
Supervisor -> Staff : hires
Assessor -> Contribution : assesses
Sponsor -> Funds : dedicates
Sponsor -> Contribution : rewards

@enduml
